[build]
  base = "city-smiles-dental/city-smiles-dental/frontend"
  command = "npm run build"
  publish = "city-smiles-dental/city-smiles-dental/frontend/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
